server:
  port: 9092

spring:
  application:
    name: persistence
  datasource:
    url: jdbc:mysql://localhost:3306/cogent-appointment
    username: newuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
        generate_statistics: true
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
      show-sql: true
      generate-ddl: true
      open-in-view: false

  main:
    allow-bean-definition-overriding: true


  jpa:
    properties.hibernate:
      enable_lazy_load_no_trans: true