server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cogent-admin
<<<<<<< HEAD
    username: sauravi
    password: Test@123##
=======
    username: cogent
    password: cogent
>>>>>>> 575af6fad305579dcafd6f5ada3f65ecb23a71d3
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate_statistics: true
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
    open-in-view: false

  jackson:
    deserialization.fail-on-unknown-properties: false

  minio:
    url: http://localhost:9000
    bucket: cogent
    access-key: minioadmin
    secret-key: minioadmin
