server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cogent-admin
    username: newuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate_statistics: true
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
      cache:
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        use_second_level_cache: true
        use_query_cache: true
    show-sql: true
    generate-ddl: true
    open-in-view: false

  jackson:
    deserialization.fail-on-unknown-properties: false

#APPOINTMENT RESERVATION PROPERTIES
# Appointment Reservation Scheduler runs in 2 minutes
# & automatically deletes after 5 minutes of its created date
reservation:
  schedulerTimeInMilliSeconds: 120000
  deleteIntervalInMinutes: 5
