server:
  port: 7072
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cogent-admin
    username: newuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate_statistics: true
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
    open-in-view: false


  jackson:
    deserialization.fail-on-unknown-properties: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20000MB
      max-request-size: 215000MB