server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esewa-appointment
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false

  jackson:
    deserialization.fail-on-unknown-properties: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20000MB
      max-request-size: 215000MB


#hmac
  #HmacSHA512 admin:eab85708-0215-4f74-b646-a67e718cf332:030932309636768:PoZuLmmyKdetzlO+nWDn+FWIh+wh581DOTz0ElMErwBOPGGNeDo5tSy69L09QP1zAPrmo5CnEd5ae3dtfkALAA==