server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cogent-appointment
    username: cogent
    password: cogent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate_statistics: true
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
    open-in-view: false

  jackson:
    deserialization.fail-on-unknown-properties: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20000MB
      max-request-size: 215000MB


#hmac :HmacSHA512 admin:eab85708-0215-4f74-b646-a67e718cf332:009124699369179:6dvfnUIrT2E1WFDMQ5XAPU5IhlnUTnZqNYivaNR0rK6/bDTas5eF95K8fLNz9s6CMk0KQaupn76Y4muVL3cSIQ==